### ISSUE TITLE
Add tags for `host` vs `container` for the controls

### ISSUE THREAD

**Issue by aaronlippold** [mitre/canonical-ubuntu-20.04-lts-stig-baseline#11]
add a 

```ruby 
tag 'host'
or
tag 'container'
or 
tag 'host','container'
```

to each control as appropriate for that controls' context

**Comment by HackerShark** [comment]
Will work on this

**Comment by aaronlippold** [comment]
This is also a good opportunity that we covered all the NA conditions correctly

**Comment by HackerShark** [comment]
Solved by [fe4d577](https://github.com/mitre/canonical-ubuntu-20.04-lts-stig-baseline/commit/fe4d577826c1b870f08644d00040fc376fe7e290)
