### ISSUE TITLE
Create a file that lists the controls that are NA or applicable to containers for folks to have as a reference as we did for RHEL7/8

### ISSUE THREAD

**Issue by aaronlippold** [mitre/canonical-ubuntu-20.04-lts-stig-baseline#9]

**Comment by HackerShark** [comment]
Currently creating the xlsx file

**Comment by HackerShark** [comment]
Solved in commit [2ffc7f8](https://github.com/mitre/canonical-ubuntu-20.04-lts-stig-baseline/pull/2/commits/2ffc7f8b84a1dcdb582b9a0c033f2896e8650ddd)
